# Generated by Django 3.2.7 on 2021-11-27 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PublicUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=64)),
                ('pass_hash', models.CharField(max_length=128)),
                ('address', models.CharField(max_length=256)),
                ('verified', models.BooleanField(default=False)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('image', models.ImageField(default='profile_images/default_profile.png', upload_to='profile_images')),
            ],
        ),
        migrations.CreateModel(
            name='ProduceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produce_name', models.CharField(max_length=64)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gardenApp.publicuser')),
            ],
        ),
        migrations.CreateModel(
            name='Produce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produce_name', models.CharField(max_length=64)),
                ('weight', models.FloatField()),
                ('fruits', models.BooleanField()),
                ('veggies', models.BooleanField()),
                ('date_created', models.DateField(auto_now_add=True)),
                ('image', models.ImageField(default='produce_images/default_produce.jpg', upload_to='produce_images')),
                ('description', models.TextField(null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gardenApp.publicuser')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.TextField()),
                ('dateTime', models.DateTimeField(auto_now_add=True)),
                ('chatID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gardenApp.chat')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gardenApp.publicuser')),
            ],
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('produce_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gardenApp.produce')),
                ('reciever', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gardenApp.publicuser')),
            ],
        ),
        migrations.AddField(
            model_name='chat',
            name='user1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user1', to='gardenApp.publicuser'),
        ),
        migrations.AddField(
            model_name='chat',
            name='user2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user2', to='gardenApp.publicuser'),
        ),
        migrations.AlterUniqueTogether(
            name='chat',
            unique_together={('user1', 'user2')},
        ),
    ]
