# Generated by Django 3.2.7 on 2021-11-26 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gardenApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicuser',
            name='image',
            field=models.ImageField(null=True, upload_to='profile_images'),
        ),
    ]
