# Generated by Django 3.2.7 on 2021-11-27 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gardenApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producerequest',
            name='fruits',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producerequest',
            name='veggies',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
