# Generated by Django 3.2.7 on 2021-11-27 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gardenApp', '0002_auto_20211127_2003'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producerequest',
            old_name='user',
            new_name='owner',
        ),
    ]
