# Generated by Django 3.2.7 on 2021-11-26 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gardenApp', '0002_publicuser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicuser',
            name='image',
            field=models.ImageField(default='/static/img/default_profile.png', null=True, upload_to='profile_images'),
        ),
    ]
