# Generated by Django 3.2.7 on 2021-11-28 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gardenApp', '0003_rename_user_producerequest_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='reciever',
        ),
    ]
