# Generated by Django 3.2.7 on 2021-11-28 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gardenApp', '0004_remove_donation_reciever'),
    ]

    operations = [
        migrations.AddField(
            model_name='produce',
            name='donated',
            field=models.BooleanField(default=False),
        ),
    ]
