# Generated by Django 3.2.7 on 2021-11-26 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gardenApp', '0004_alter_publicuser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicuser',
            name='image',
            field=models.ImageField(default='default_profile.png', upload_to='profile_images'),
        ),
    ]
