# Generated by Django 3.2.7 on 2021-11-28 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gardenApp', '0005_produce_donated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producerequest',
            name='weight',
            field=models.FloatField(),
        ),
    ]
