# Generated by Django 3.2.7 on 2021-11-27 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gardenApp', '0007_auto_20211127_0538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='dateTime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
