# Generated by Django 3.2.7 on 2021-11-27 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gardenApp', '0008_alter_message_datetime'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chat',
            unique_together={('user1', 'user2')},
        ),
    ]
